# Generated by Django 4.2.16 on 2026-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("axis_saas", "0009_add_school_feature_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fee_custom_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Saved custom fee line items for vouchers",
            ),
        ),
    ]
